# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Email',
        ),
    ]
